---
- name: ufw installation
  become: 'yes'
  become_method: sudo
  package:
    name: "ufw"
    state: latest
    install_recommends: 'no'
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - packages
    - security
    - ufw

- name: redhat family epel installation
  become: 'yes'
  become_method: sudo
  package:
    name: "epel-release"
    state: latest
  when: ansible_distribution == "RedHat"
  tags:
    - yum
    - packages
    - security

- name: firewalld installation
  become: 'yes'
  become_method: sudo
  package:
    name: "firewalld"
    state: latest
  when: ansible_os_family == "RedHat"
  tags:
    - yum
    - packages
    - security
    - firewalld

- name: firewalld-python installation
  become: 'yes'
  become_method: sudo
  package:
    name: "python-firewall"
    state: latest
  when: ansible_os_family == "RedHat"
  tags:
    - yum
    - packages
    - security
    - firewalld

- name: set ufw IPT_SYSCTL
  become: 'yes'
  become_method: sudo
  lineinfile:
    regexp: "^IPT_SYSCTL="
    line: "IPT_SYSCTL=/etc/sysctl.conf"
    dest: /etc/default/ufw
    mode: 0640
    state: present
    create: 'no'
    backrefs: 'yes'
  tags:
    - ufw
    - security
  when: ansible_os_family == "Debian"

- name: reset ufw
  become: 'yes'
  become_method: sudo
  ufw:
    state: reset
  when: ansible_os_family == "Debian"
  tags:
    - ufw
    - security

- name: allow ssh ufw
  become: 'yes'
  become_method: sudo
  ufw:
    rule: allow
    src: "{{ item }}"
    port: 22
    proto: tcp
  with_items:
    - "{{ sshd_admin_net }}"
  when: ansible_os_family == "Debian"
  tags:
    - ufw
    - ssh
    - security

- name: enable ufw
  become: 'yes'
  become_method: sudo
  ufw:
    state: enabled
    policy: deny
    logging: low
  when: ansible_os_family == "Debian"
  tags:
    - ufw
    - security

- name: stat firewalld conf
  become: 'yes'
  become_method: sudo
  stat:
    path: /etc/firewalld/firewalld.conf
  register: firewalldconf

- name: set firewalld DefaultZone
  become: 'yes'
  become_method: sudo
  lineinfile:
    regexp: "^DefaultZone="
    line: "DefaultZone=public"
    dest: /etc/firewalld/firewalld.conf
    mode: 0640
    state: present
    create: 'no'
    backrefs: 'yes'
  when: firewalldconf.stat.exists
  tags:
    - firewalld
    - security

- name: enable firewalld
  become: 'yes'
  become_method: sudo
  service:
    name: firewalld
    state: started
    enabled: 'yes'
  when: firewalldconf.stat.exists
  tags:
    - firewalld
    - security

- name: allow firewalld ssh
  become: 'yes'
  become_method: sudo
  firewalld:
    service: ssh
    permanent: true
    state: enabled
    zone: public
  when: ansible_os_family == "RedHat"
  tags:
    - firewalld
    - security
...
