---
- name: reset ufw
  become: yes
  become_method: sudo
  ufw:
    state: reset
  when: ansible_distribution == "Ubuntu"
  tags:
    - ufw
    - security

- name: allow ssh ufw
  become: yes
  become_method: sudo
  ufw:
    rule: allow
    src: "{{ item }}"
    port: 22
    proto: tcp
  with_items:
    - "{{ sshd_admin_net }}"
  when: ansible_distribution == "Ubuntu"
  tags:
    - ufw
    - ssh
    - security

- name: enable ufw
  become: yes
  become_method: sudo
  ufw:
    state: enabled
    policy: deny
    logging: low
  when: ansible_distribution == "Ubuntu"
  tags:
    - ufw
    - security

- name: stat firewalld conf
  become: yes
  become_method: sudo
  stat:
    path: /etc/firewalld/firewalld.conf
  register: firewalldconf

- name: set firewalld DefaultZone
  become: yes
  become_method: sudo
  lineinfile:
    regexp: "^DefaultZone="
    line: "DefaultZone=public"
    dest: /etc/firewalld/firewalld.conf
    mode: 0640
    state: present
    create: no
    backrefs: yes
  when: firewalldconf.stat.exists
  tags:
    - firewalld
    - security

- name: enable firewalld
  become: yes
  become_method: sudo
  service:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"
  tags:
    - firewalld
    - security

- name: allow firewalld ssh
  become: yes
  become_method: sudo
  firewalld:
    service: ssh
    permanent: true
    state: enabled
    zone: public
  when: ansible_distribution == "CentOS"
  tags:
    - firewalld
    - security
...
