---
- name: disable net modules
  become: yes
  become_method: sudo
  template:
    src: disablenet.conf.j2
    dest: /etc/modprobe.d/disablenet.conf
    backup: yes
    mode: 0644
    owner: root
    group: root
  tags:
    - modprobe
    - security
...
