---
- name: common-password
  become: 'yes'
  become_method: sudo
  template:
    src: etc/pam.d/common-password.j2
    dest: /etc/pam.d/common-password
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - common-password
    - pam
    - security

- name: common-auth
  become: 'yes'
  become_method: sudo
  template:
    src: etc/pam.d/common-auth.j2
    dest: /etc/pam.d/common-auth
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - common-auth
    - pam
    - security

- name: common-account
  become: 'yes'
  become_method: sudo
  template:
    src: etc/pam.d/common-account.j2
    dest: /etc/pam.d/common-account
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - common-account
    - pam
    - security

- name: login
  become: 'yes'
  become_method: sudo
  template:
    src: etc/pam.d/login.j2
    dest: /etc/pam.d/login
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  when: ansible_os_family == "Debian"
  tags:
    - login
    - pam
    - security

- name: pwquality
  become: 'yes'
  become_method: sudo
  template:
    src: etc/security/pwquality.conf.j2
    dest: /etc/security/pwquality.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  when: ansible_os_family == "RedHat"
  tags:
    - pwquality
    - pam
    - security

- name: authconfig - passwdalgorithm
  become: 'yes'
  become_method: sudo
  lineinfile:
    regexp: "^PASSWDALGORITHM="
    line: "PASSWDALGORITHM=sha512"
    dest: /etc/sysconfig/authconfig
    mode: 0644
    state: present
    create: 'no'
    backrefs: 'yes'
  when: ansible_os_family == "RedHat"
  notify:
    - update authconfig
  tags:
    - rc
    - authconfig
    - security

- name: authconfig - usepwquality
  become: 'yes'
  become_method: sudo
  lineinfile:
    regexp: "^USEPWQUALITY="
    line: "USEPWQUALITY=yes"
    dest: /etc/sysconfig/authconfig
    mode: 0644
    state: present
    create: 'no'
    backrefs: 'yes'
  when: ansible_os_family == "RedHat"
  notify:
    - update authconfig
  tags:
    - rc
    - authconfig
    - security

# CCE-27286-4
- name: remove nullok from system-auth
  become: 'yes'
  become_method: sudo
  replace:
    dest: /etc/pam.d/system-auth
    follow: 'yes'
    regexp: 'nullok'
    backup: 'yes'
  when: ansible_os_family == "RedHat"
  tags:
    - system-auth
    - security
    - pam

- name: remove nullok from password-auth
  become: 'yes'
  become_method: sudo
  replace:
    dest: /etc/pam.d/password-auth
    follow: 'yes'
    regexp: 'nullok'
    backup: 'yes'
  when: ansible_os_family == "RedHat"
  tags:
    - password-auth
    - security
    - pam

- name: stat libuser
  become: 'yes'
  become_method: sudo
  stat:
    path: /etc/libuser.conf
  register: libuser

- name: set libuser sha512
  become: 'yes'
  become_method: sudo
  replace:
    regexp: 'crypt_style(\s+.*)'
    replace: "crypt_style = sha512"
    dest: /etc/libuser.conf
    mode: 0644
  when: libuser.stat.exists
  tags:
    - libuser
    - security

- name: set system-auth remember
  become: 'yes'
  become_method: sudo
  replace:
    regexp: 'use_authtok(\s+.*)'
    replace: "use_authtok remember=5"
    dest: /etc/pam.d/system-auth
    follow: 'yes'
  when: ansible_os_family == "RedHat"
  tags:
    - system-auth
    - security
...
