---
- name: remove cron.deny and at.deny
  become: 'yes'
  become_method: sudo
  file:
    path: "{{ item }}"
    state: absent
  ignore_errors: true
  with_items:
    - /etc/cron.deny
    - /etc/at.deny
    - /etc/cron.allow
    - /etc/at.allow
  tags:
    - at
    - cron
    - security

- name: allow root cron and at
  become: 'yes'
  become_method: sudo
  lineinfile:
    line: "root"
    dest: "{{ item }}"
    mode: 0600
    state: present
    create: 'yes'
  with_items:
    - /etc/cron.allow
    - /etc/at.allow
  tags:
    - at
    - cron
    - security

# CCE-80345-2
- name: mask atd
  become: 'yes'
  become_method: sudo
  systemd:
    name: atd
    masked: 'yes'
    enabled: 'no'
    state: stopped
  ignore_errors: true
  tags:
    - at
    - systemd
    - security
...
