---
- name: audit.rules
  become: yes
  become_method: sudo
  template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/hardening.rules
    backup: yes
    mode: 0600
    owner: root
    group: root
  notify:
      - generate auditd
      - restart auditd
  tags:
    - auditd
    - audit.rules
    - security
...
