---
- name: disablemod.conf
  become: yes
  become_method: sudo
  file:
    state: touch
    path: /etc/modprobe.d/disablemod.conf
    owner: root
    group: root
    mode: 0644

- name: disable misc kernel modules
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/modprobe.d/disablemod.conf
    line: "install {{ item }} /bin/true"
  with_items:
    - "{{ misc_modules_blacklist }}"
  tags:
    - modprobe
    - security
...
