---
- name: aide service
  become: yes
  become_method: sudo
  template:
    src: lib/systemd/system/aidecheck.service.j2
    dest: /lib/systemd/system/aidecheck.service
    backup: yes
    mode: 0644
    owner: root
    group: root
  when: not ansible_bios_version == "VirtualBox"
  tags:
    - aide
    - security

# CCE-26952-2
- name: aide timer
  become: yes
  become_method: sudo
  template:
    src: lib/systemd/system/aidecheck.timer.j2
    dest: /lib/systemd/system/aidecheck.timer
    backup: yes
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
    - enable aidecheck
  when: not ansible_bios_version == "VirtualBox"
  tags:
    - aide
    - security

- name: stat aide.db
  become: yes
  become_method: sudo
  stat:
    path: /var/lib/aide/aide.db.gz
  register: aidedb

# CCE-27220-3
- name: initialize aide
  become: yes
  become_method: sudo
  shell: aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz'
  when: not aidedb.stat.exists
...
