---
# CCE-80199-3

- name: set path
  become: 'yes'
  become_method: sudo
  lineinfile:
    regexp: "^PATH="
    line: 'PATH="/usr/local/bin:/usr/bin:/bin/"'
    dest: /etc/environment
    mode: 0644
    state: present
    create: 'no'
    backrefs: 'yes'
  tags:
    - path
    - security

- name: path script
  become: 'yes'
  become_method: sudo
  template:
    src: etc/profile.d/initpath.sh.j2
    dest: /etc/profile.d/initpath.sh
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - path
    - security
...
