---
- name: configure apt
  become: 'yes'
  become_method: sudo
  lineinfile:
    dest: /etc/apt/apt.conf.d/98apt-conf
    mode: 0644
    state: present
    create: 'yes'
    line: "{{ item }}"
  with_items:
    - 'APT::Get::AllowUnauthenticated "false";'
    - 'APT::Get::AutomaticRemove "true";'
    - 'APT::Install-Recommends "false";'
    - 'APT::Install-Suggests "false";'
    - 'APT::Periodic::AutocleanInterval "7";'
    - 'Acquire::http::AllowRedirect "false";'
    - 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - security

- name: configure dpkg noexec
  become: 'yes'
  become_method: sudo
  lineinfile:
    dest: /etc/apt/apt.conf.d/99noexec-tmp
    mode: 0644
    state: present
    create: 'yes'
    line: "{{ item }}"
  with_items:
    - 'DPkg::Pre-Invoke {"mount -o remount,exec,nodev,nosuid /tmp";};'
    - 'DPkg::Pre-Invoke {"mount -o remount,exec,nodev,nosuid /var/tmp";};'
    - 'DPkg::Post-Invoke {"mount -o remount,mode=1777,strictatime,noexec,nodev,nosuid /tmp";};'
    - 'DPkg::Post-Invoke {"mount -o remount,mode=1777,strictatime,noexec,nodev,nosuid /var/tmp";};'
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - security
...
