---
- name: Configure auditd
  become: true
  block:
    - name: Install initscripts
      ansible.builtin.package:
        name: initscripts
        state: present
      when:
        - ansible_facts.os_family == "RedHat"

    - name: Configure Debian auditd GRUB cmdline
      ansible.builtin.lineinfile:
        line: GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX {{ grub_audit_cmdline }} {{ grub_audit_backlog_cmdline }}"
        dest: /etc/default/grub.d/99-hardening-audit.cfg
        state: present
        create: true
        mode: "0640"
        owner: root
        group: root
      when:
        - ansible_facts.os_family == "Debian"
      notify:
        - Update GRUB

    - name: Configure RedHat auditd GRUB cmdline
      ansible.builtin.command:
        cmd: grubby --update-kernel=ALL --args="{{ grub_audit_cmdline }} {{ grub_audit_backlog_cmdline }}"
      register: grubby_update_kernel
      changed_when: grubby_update_kernel.rc != 0
      failed_when: grubby_update_kernel.rc != 0
      when:
        - ansible_facts.os_family == "RedHat"
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]

    - name: Configure auditd action_mail_acct
      ansible.builtin.lineinfile:
        regexp: ^action_mail_acct =
        line: action_mail_acct = {{ auditd_action_mail_acct }}
        dest: /etc/audit/auditd.conf
        mode: "0640"
        state: present
        create: false

    - name: Configure auditd admin_space_left_action
      ansible.builtin.lineinfile:
        regexp: ^admin_space_left_action =
        line: admin_space_left_action = {{ auditd_admin_space_left_action }}
        dest: /etc/audit/auditd.conf
        mode: "0640"
        state: present
        create: false

    - name: Configure auditd disk_error_action
      ansible.builtin.lineinfile:
        regexp: ^disk_error_action =
        line: disk_error_action = {{ auditd_disk_error_action }}
        dest: /etc/audit/auditd.conf
        mode: "0640"
        state: present
        create: false

    - name: Configure auditd disk_full_action
      ansible.builtin.lineinfile:
        regexp: ^disk_full_action =
        line: disk_full_action = {{ auditd_disk_full_action }}
        dest: /etc/audit/auditd.conf
        mode: "0640"
        state: present
        create: false

    - name: Configure auditd flush
      ansible.builtin.lineinfile:
        regexp: ^flush =
        line: flush = {{ auditd_flush }}
        dest: /etc/audit/auditd.conf
        mode: "0640"
        state: present
        create: false

    - name: Configure auditd max_log_file
      ansible.builtin.lineinfile:
        regexp: ^max_log_file =
        line: max_log_file = {{ auditd_max_log_file }}
        dest: /etc/audit/auditd.conf
        mode: "0640"
        state: present
        create: false

    - name: Configure auditd max_log_file_action
      ansible.builtin.lineinfile:
        regexp: ^max_log_file_action =
        line: max_log_file_action = {{ auditd_max_log_file_action }}
        dest: /etc/audit/auditd.conf
        mode: "0640"
        state: present
        create: false

    - name: Configure auditd num_logs
      ansible.builtin.lineinfile:
        regexp: ^num_logs =
        line: num_logs = {{ auditd_num_logs }}
        dest: /etc/audit/auditd.conf
        mode: "0640"
        state: present
        create: false

    - name: Configure auditd space_left
      ansible.builtin.lineinfile:
        regexp: ^space_left =
        line: space_left = {{ auditd_space_left }}
        dest: /etc/audit/auditd.conf
        mode: "0640"
        state: present
        create: false

    - name: Configure auditd space_left_action
      ansible.builtin.lineinfile:
        regexp: ^space_left_action =
        line: space_left_action = {{ auditd_space_left_action }}
        dest: /etc/audit/auditd.conf
        mode: "0640"
        state: present
        create: false

    - name: Configure auditd name_format
      ansible.builtin.lineinfile:
        regexp: ^name_format =
        line: name_format = hostname
        dest: /etc/audit/auditd.conf
        mode: "0640"
        state: present
        create: false

    - name: Enable auditd syslog plugin
      ansible.builtin.lineinfile:
        dest: /etc/audit/plugins.d/syslog.conf
        regexp: ^active
        line: active = yes
        state: present
        mode: "0640"
        create: true

    - name: Add auditd rules
      ansible.builtin.template:
        src: "{{ hardening_rules_template }}"
        dest: /etc/audit/rules.d/hardening.rules
        backup: true
        mode: "0600"
        owner: root
        group: root
      when:
        - auditd_apply_audit_rules | bool
      notify:
        - Generate auditd rules
        - Enable auditd
