---
- name: register compilers
  become: 'yes'
  find:
    paths: ['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/snap/bin']
    patterns: "{{ compilers }}"
    file_type: any
    follow: 'yes'
    recurse: 'yes'
  register: compiler
  tags:
    - compilers

- name: restrict compiler access
  become: 'yes'
  file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: 0750
    state: file
    follow: 'yes'
  with_items:
    - "{{ compiler.files }}"
  tags:
    - compilers
...
