---
- name: Add custom facts
  become: true
  block:
    - name: Create custom facts directory
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Add ssh keys fact
      ansible.builtin.template:
        src: etc/ansible/facts.d/sshkeys.fact
        dest: /etc/ansible/facts.d/sshkeys.fact
        mode: "0755"
        owner: root
        group: root

- name: Stat IPv6 status
  become: true
  ansible.builtin.stat:
    path: /proc/sys/net/ipv6
  register: stat_ipv6

- name: Set IPv6 fact
  ansible.builtin.set_fact:
    system_has_ipv6: "{{ stat_ipv6.stat.exists }}"

- name: Set sysctl configuration directory as fact
  block:
    - name: Stat /usr/lib/sysctl.d/ exists
      ansible.builtin.stat:
        path: /usr/lib/sysctl.d/
      register: usr_lib_sysctl_d

    - name: Set sysctl fact
      ansible.builtin.set_fact:
        usr_lib_sysctl_d_dir: "{{ true if usr_lib_sysctl_d.stat.exists else false }}"

- name: Set crypto-policies config as fact
  block:
    - name: Stat crypto-policies config
      ansible.builtin.stat:
        path: /etc/crypto-policies/config
      register: stat_crypto_policies_config

    - name: Set config fact
      ansible.builtin.set_fact:
        crypto_policies_config: "{{ stat_crypto_policies_config.stat.exists }}"

- name: Get PAM version
  block:
    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Get libpam version in Debian family
      ansible.builtin.set_fact:
        pam_version: "{{ ansible_facts.packages['libpam-modules'][0].version }}"
      when:
        - ansible_os_family == "Debian"
        - "'libpam-modules' in ansible_facts.packages"

    - name: Get libpam version in RedHat family
      ansible.builtin.set_fact:
        pam_version: "{{ ansible_facts.packages['pam'][0].version }}"
      when:
        - ansible_os_family == "RedHat"
        - "'pam' in ansible_facts.packages"
  when:
    - manage_pam

- name: Set hashing algorithm for password (yescrypt|sha512)
  ansible.builtin.set_fact:
    password_algorithm: "{{ 'yescrypt' if (pam_version is version('1.4.0', '>=')) else 'sha512' }}"
  when:
    - manage_pam

- name: Update current facts
  ansible.builtin.setup:
