---
- name: hosts.allow
  become: true
  ansible.builtin.template:
    src: etc/hosts.allow.j2
    dest: /etc/hosts.allow
    backup: true
    mode: 0644
    owner: root
    group: root
  tags:
    - hosts.allow

- name: hosts.deny
  become: true
  ansible.builtin.template:
    src: etc/hosts.deny.j2
    dest: /etc/hosts.deny
    backup: true
    mode: 0644
    owner: root
    group: root
  tags:
    - hosts.deny
...
